/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "OS_ReactionGame_ee.h"
#include "OS_ReactionGame_ee_tracing.h"
#include "SEVEN_C_aliases.h"
#include "SEVEN_C.h"
#include "SEVEN_B_aliases.h"
#include "SEVEN_B.h"
#include "SEVEN_A_aliases.h"
#include "SEVEN_A.h"
#include "SEVEN_D_aliases.h"
#include "SEVEN_D.h"
#include "SEVEN_E_aliases.h"
#include "SEVEN_E.h"
#include "SEVEN_F_aliases.h"
#include "SEVEN_F.h"
#include "SEVEN_G_aliases.h"
#include "SEVEN_G.h"
#include "SEVEN_DP_aliases.h"
#include "SEVEN_DP.h"
#include "SEVEN_SELECT_aliases.h"
#include "SEVEN_SELECT.h"
#include "SEVEN_reg.h"
#include "BUTTON_1_aliases.h"
#include "BUTTON_1.h"
#include "isr_Button.h"
#include "BUTTON_2_aliases.h"
#include "BUTTON_2.h"
#include "BUTTON_3_aliases.h"
#include "BUTTON_3.h"
#include "BUTTON_4_aliases.h"
#include "BUTTON_4.h"
#include "LED_red_aliases.h"
#include "LED_red.h"
#include "LED_yellow_aliases.h"
#include "LED_yellow.h"
#include "LED_green_aliases.h"
#include "LED_green.h"
#include "UART_LOG.h"
#include "RGB_PWM_red.h"
#include "PWM_Clock.h"
#include "RGB_PWM_green.h"
#include "RGB_PWM_blue.h"
#include "RGB_R_aliases.h"
#include "RGB_R.h"
#include "RGB_G_aliases.h"
#include "RGB_G.h"
#include "RGB_B_aliases.h"
#include "RGB_B.h"
#include "LED_PWM_RED.h"
#include "LED_PWM_Clock.h"
#include "LED_PWM_GREEN.h"
#include "LED_PWM_YELLOW.h"
#include "UART_LOG_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

